### ISSUE TITLE
Dropping video frames results in frozen video stream

### ISSUE THREAD

**Issue by fabrpece** [puku0x/cvdrone#12]
Hi,

thanks a lot for the good work! I am playing around with your test example, and I am facing a pretty weird bug/problem.

Essentially, in a very unreliable way, the video stream from the drone suddenly freezes, causing opencv to always show the very last frame grabbed. I have placed few debugging output here and there, and I have found out that when the freeze happens, in the method 
ARDrone::getVideo 
the statement 
av_read_frame(pFormatCtx, &packet) 
is never >= 0, hence no packets are parsed and the loop in 
ARDrone::loopVideo 
breaks.

I am not sure what could be the problem. I am on Ubuntu 14.04, Ar.Drone Ver. 2.4.8. Have you ever faced this problem? I have tried to change sleeping times (increasing/decreasing them), with no luck. Also, this is completely random. Sometimes I am able to fly and show video without any problem, but most of the time I can only show the video for few seconds. All other communication work fine. Another interesting behavior is that the program has about 5--8 seconds hanging time between when the Drone version is printed and when the first frame comes in (or at least is shown by opencv).

Thanks a lot for your help!

-Fabrizio

**Comment by puku0x** [comment]
Nothing happened ?
