### ISSUE TITLE
Correcting English

### ISSUE THREAD

**Issue by puku0x** [puku0x/cvdrone#14]
Hi all,

Thank you very much for using CV Drone.
The library grew up as a useful one and helped many AR.Drone users.

However, I think I wrote a lot of wrong English in comment.

Of course, it is because of my lack of knowledge of English, but if it is possible, please help me.

Sincerely,
puku0x

**Comment by anfedres** [comment]
Tell me what do you need. English is not my native language. But I can help.

**Comment by puku0x** [comment]
Oh, thank you anfedres.

All comments in source codes and articles in [Wiki](https://github.com/puku0x/cvdrone/wiki) are written in English.

If you find wrong spellings, strange idioms and grammars in them, please tell me because I am not a native speaker and I am not sure they are understandable for native speakers.

Regards,
puku0x

**Comment by anfedres** [comment]
They are. Don't worry. You are doing great. 

anfedres

**Comment by puku0x** [comment]
Thank you.
I deeply appreciate it.
