### ISSUE TITLE
PID controller

### ISSUE THREAD

**Issue by daniel8x** [puku0x/cvdrone#20]
Does the library support PID controller ?

Thanks

**Comment by zawwaithant** [comment]
Hello , I tried the hint #20.
I worked and done well . but Which amount of ki and kd value should be set for my experiment?
I used < 8 inch x 8 inch > red target circle and drone's predefined height above the target is at 7 feet.
I allowed the moving velocity of the target not to exceed the maximum speed of the AR.Drone.
I tried the codes of hint #20 in default setting of ki=0.000 and kd=0.0000, it works well. But, it does not reach the purpose of tracking and following the Target Image. Why?. Which Amount of ki and kd value should i used for my testing? or What is your choice for Ki and Kd values?
 
Please., sharing knowledge ?

**Comment by johneyoh** [comment]
// Marker
	cv::Point marker(binalized.cols / 2, binalized.rows / 2);

why binalized not defined!??

**Comment by puku0x** [comment]
Sorry, it is my mistake. Please fix it like this.
```
cv::Point marker(0, 0);

**Comment by kyawthuyalwin** [comment]
hay ,,,, friends,... could you describe your Kp , Ki and Kd tuned values for #20...?
