### ISSUE TITLE
How to run a Windows example (2.0)

### ISSUE THREAD

**Issue by Zepolrotia92** [puku0x/cvdrone#34]
Good morning everyone!

Going back to this question (https://github.com/puku0x/cvdrone/issues/22), as I'm also newbie with this and I'm stuck in the same issue.

In my case (using W8/10) is it needed to modify the 'makefile' in (...)\cvdroneEDIT\build\mingw to run the samples? In that case, do I have to replace, for instance, the "PROGRAM = " statement (appearing 'Test.exe') just for 'kalman_tracking.cpp'?

This is what I've done until now, unsuccessfully.

Thank you for your kind support!

**Comment by Zepolrotia92** [comment]
Do I perhaps need to substitute the content of 'main.cpp' file inside (...)\cvdroneEDIT\src for the one of the sample of my choice?

**Comment by puku0x** [comment]
Perhaps yes.

**Comment by Zepolrotia92** [comment]
Hi puku0x,

Thanks a lot for your help, I finally managed to take off my drone hahaha!

Could you please give me also a hand with this question (https://github.com/puku0x/cvdrone/issues/36), which is also mine -although it appears with a different nickname?

Thank you in advance!

Regards,
Aitor
