### ISSUE TITLE
Detect tags

### ISSUE THREAD

**Issue by venkathindusthani** [puku0x/cvdrone#38]
Hi,
Your cvdrone application is very useful to me in my project. I use your application code for reference. I liked the design how you developed. 
I'm thinking to integrate April Tags detection libraries with this application. Can you help me on this, if you have already done similar kind of integration with your application?
Thank you so much in advance,

**Comment by puku0x** [comment]
Hi,

Thank you for your comment.

I wrote a maker-based AR sample before.
https://github.com/puku0x/cvdrone/blob/master/samples/sample_marker_based_ar.cpp

The sample uses this kind of marker, similar to April Tags..
![ArUco Marker](https://raw.githubusercontent.com/puku0x/cvdrone/master/samples/marker.png)

**Comment by puku0x** [comment]
One more thing !
Recently, CV Drone bundled OpeCV3.1 with [extra modules](https://github.com/Itseez/opencv_contrib) .

You can also use the OpenCV's ArUco integration.
http://docs.opencv.org/master/d5/dae/tutorial_aruco_detection.html#gsc.tab=0
https://github.com/Itseez/opencv_contrib/blob/master/modules/aruco/samples/detect_markers.cpp

**Comment by venkathindusthani** [comment]
Thank you so much,
I will explore into the topics u mentioned
