### ISSUE TITLE
unit of velocity

### ISSUE THREAD

**Issue by msoar2** [puku0x/cvdrone#49]
Hello!!
your AR drone code is really awesome
i just wonder what unit of velocity of drone?

and also roll, yaw and pitch

thank you!!!

**Comment by puku0x** [comment]
Hi !

The unit of velocities which returned by ARDrone::getVelocity() is **[m/s]**.

Moreover, the unit of roll, pitch and yaw angles is **[rad]**.
If you would like to use them in degrees, please use RAD_TO_DEG.

```c++
// Convert angles from [rad] to [deg]
double roll  = ardrone.getRoll()  * RAD_TO_DEG;
double pitch = ardrone.gerPitch() * RAD_TO_DEG;
double yaw   = ardrone.gerYaw()   * RAD_TO_DEG;
```

Regards,
puku

**Comment by msoar2** [comment]
really appreciate!! thanks
