### ISSUE TITLE
I cannot get any navigation data(Altitude, battery, and so on) - Using VS 2015

### ISSUE THREAD

**Issue by ironluffy** [puku0x/cvdrone#59]
Hello

I just started to use cv-drone.
Even though I didn't modify at all, battery percentage, altitudes are all zero actually.
I'm using VS 2015, Windows 10. What should I do??
Help

**Comment by puku0x** [comment]
I heard the same issue happened on Mac before.

[Battery percentage and altitude percentage is always 0 #30](https://github.com/puku0x/cvdrone/issues/30)

Unfortunately, I have no idea why this happen and how to solve it 😫

**Comment by ironluffy** [comment]
Thank you for review this.
I just used Ubuntu 12 and there was no problem
I will close this issue
