### ISSUE TITLE
Multi-platform FTP Client

### ISSUE THREAD

**Issue by puku0x** [puku0x/cvdrone#7]
Old version of CV Drone can get "version.txt" from AR.Drone, why not the latest one can do it ?

TODO：
- Implement FTP client
- Get "version.txt" from port 5551 of AR.Drone.
- Confirm it runs on Win/Mac/Linux.

REQUIREMENTS:
- Knowledge of FTP
- Beautiful codes
- Your enthusiasm

I would appreciate if you contribute to CV Drone.

Regards,
puku0x

**Comment by yunnimu** [comment]
hello I have the same problem

ERROR: connect() failed. (../../src/ardrone/tcp.cpp, 76)
TCPSocket::open(port=5551) failed. (../../src/ardrone/version.cpp, 42)
Failed to initialize.

how to solve this problem?

**Comment by puku0x** [comment]
Hi, thank you for your report.

Are your drone and your PC connected to the same network ?

**Comment by yunnimu** [comment]
Yes I wanna conect my drone to my pc but the eror like that.. And i try to
connect my drone to other pc,but the problem is same..

Regards,
Yunni Muharani
Mobile : +6281904043349
